// Code generated by tgcomp/internal/gen; DO NOT EDIT.

package tgcomp

import (
	"github.com/voilelab/toolgui/toolgui/tgcomp/tcchat"
	"github.com/voilelab/toolgui/toolgui/tgframe"
)

// ChatInputConf is the configuration for the ChatInput component.
type ChatInputConf = tcchat.ChatInputConf

// ChatInput draws a box to send a chat message, and returns the message and
// true on the run its send starts. Every other run returns "" and false. The
// box is emptied once a message is sent.
//
// Written in the page's main container, it is pinned to the bottom of the
// page wherever it is written, so it may come before the messages it adds.
// In any other container it stays where it is written.
func ChatInput(c *tgframe.Container, placeholder string, conf ...*ChatInputConf) (string, bool) {
	return tcchat.ChatInput(c, placeholder, conf...)
}

// ChatMessageConf is the configuration for the ChatMessage component.
type ChatMessageConf = tcchat.ChatMessageConf

// ChatMessage draws a message of a chat, sent by role, and returns the
// container its content goes in. "user" and "human" are drawn as the user,
// "assistant" and "ai" as the assistant; any other role is drawn by name.
func ChatMessage(c *tgframe.Container, role string, conf ...*ChatMessageConf) *tgframe.Container {
	return tcchat.ChatMessage(c, role, conf...)
}
