// Code generated by tgcomp/internal/gen; DO NOT EDIT.

package tgcomp

import (
	"github.com/voilelab/toolgui/toolgui/tgcomp/tccontent"
	"github.com/voilelab/toolgui/toolgui/tgframe"
	"iter"
	"net/url"
)

// BadgeConf is the configuration for the Badge component.
type BadgeConf = tccontent.BadgeConf

// Badge show a short label, for a status or a tag next to other content.
func Badge(c *tgframe.Container, text string, conf ...*BadgeConf) {
	tccontent.Badge(c, text, conf...)
}

// CaptionConf is the configuration for the Caption component.
type CaptionConf = tccontent.CaptionConf

// Caption show a small dimmed text, for a note next to what it explains.
func Caption(c *tgframe.Container, text string, conf ...*CaptionConf) {
	tccontent.Caption(c, text, conf...)
}

// CodeConf provide extra config for Code Component.
type CodeConf = tccontent.CodeConf

// Code create a code block with syntax highlight.
func Code(c *tgframe.Container, code string, conf ...*CodeConf) {
	tccontent.Code(c, code, conf...)
}

// DividerConf is the configuration for the Divider component.
type DividerConf = tccontent.DividerConf

// Divider create a horizontal line.
func Divider(c *tgframe.Container, conf ...*DividerConf) {
	tccontent.Divider(c, conf...)
}

// ImageFormat is the format of the image
type ImageFormat = tccontent.ImageFormat

const (
	ImageFormatPNG  = tccontent.ImageFormatPNG
	ImageFormatJPEG = tccontent.ImageFormatJPEG
)

// ImageConf is the configuration for the Image component
type ImageConf = tccontent.ImageConf

// Image show an image.
func Image(c *tgframe.Container, img any, conf ...*ImageConf) {
	tccontent.Image(c, img, conf...)
}

// LatexConf is the configuration for the Latex component.
type LatexConf = tccontent.LatexConf

// Latex renders text as LaTeX.
func Latex(c *tgframe.Container, text string, conf ...*LatexConf) {
	tccontent.Latex(c, text, conf...)
}

// LinkConf is the configuration for the Link component.
type LinkConf = tccontent.LinkConf

// Link create a link component.
func Link(c *tgframe.Container, text, url string, conf ...*LinkConf) {
	tccontent.Link(c, text, url, conf...)
}

// LinkButtonConf is the configuration for the LinkButton component.
type LinkButtonConf = tccontent.LinkButtonConf

// LinkButton create a link that is drawn as a button. It navigates rather
// than reporting a click, so unlike Button it returns nothing and keeps no
// state.
func LinkButton(c *tgframe.Container, text, url string, conf ...*LinkButtonConf) {
	tccontent.LinkButton(c, text, url, conf...)
}

// MarkdownConf is the configuration for the Markdown component.
type MarkdownConf = tccontent.MarkdownConf

// Markdown render markdown to html.
func Markdown(c *tgframe.Container, markdown string, conf ...*MarkdownConf) {
	tccontent.Markdown(c, markdown, conf...)
}

// MetricConf is the configuration for the Metric component.
type MetricConf = tccontent.MetricConf

// Metric show a labelled value, with an optional delta under it.
func Metric(c *tgframe.Container, label, value string, conf ...*MetricConf) {
	tccontent.Metric(c, label, value, conf...)
}

// PageLinkConf is the configuration for the PageLink component.
type PageLinkConf = tccontent.PageLinkConf

// PageLink create a link to page of this app, opened with query as its
// [tgframe.Params.Query]. It is a real link, so middle-click and copying it
// work. It takes a page name, not a URL, so it cannot point off the app.
// An unknown page fails the component.
func PageLink(c *tgframe.Container, text, page string, query url.Values, conf ...*PageLinkConf) {
	tccontent.PageLink(c, text, page, query, conf...)
}

// SubtitleConf is the configuration for the Subtitle component.
type SubtitleConf = tccontent.SubtitleConf

// Subtitle create a subtitle.
func Subtitle(c *tgframe.Container, text string, conf ...*SubtitleConf) {
	tccontent.Subtitle(c, text, conf...)
}

// TextConf is the configuration for the Text component.
type TextConf = tccontent.TextConf

// Text show a text.
func Text(c *tgframe.Container, text string, conf ...*TextConf) {
	tccontent.Text(c, text, conf...)
}

// TitleConf is the configuration for the Title component.
type TitleConf = tccontent.TitleConf

// Title show a title.
func Title(c *tgframe.Container, text string, conf ...*TitleConf) {
	tccontent.Title(c, text, conf...)
}

// WriteStreamConf is the configuration for the WriteStream component.
type WriteStreamConf = tccontent.WriteStreamConf

// WriteStream writes the chunks of seq into one Markdown as they arrive, and
// returns the whole text. The first error of seq stops it, and is returned
// with the text before it.
//
// The growing text is sent at most once per Conf.Interval, not once per chunk.
//
// seq runs on a goroutine of its own and must not draw components. WriteStream
// waits for it to return, so build it on [tgframe.Params.Context]: a cut run
// then ends it at once.
func WriteStream(c *tgframe.Container, seq iter.Seq2[string, error], conf ...*WriteStreamConf) (string, error) {
	return tccontent.WriteStream(c, seq, conf...)
}
