// Code generated by tgcomp/internal/gen; DO NOT EDIT.

package tgcomp

import (
	"github.com/voilelab/toolgui/toolgui/tgcomp/tcdata"
	"github.com/voilelab/toolgui/toolgui/tgframe"
	"time"
)

// ChartKind is the shape a chart is drawn in.
type ChartKind = tcdata.ChartKind

const (
	// ChartKindLine draws one line per series.
	ChartKindLine = tcdata.ChartKindLine

	// ChartKindBar draws one bar per value, grouped by label.
	ChartKindBar = tcdata.ChartKindBar

	// ChartKindArea draws one line per series, filled to the axis.
	ChartKindArea = tcdata.ChartKindArea

	// ChartKindScatter draws one marker per point, on two value axes.
	ChartKindScatter = tcdata.ChartKindScatter
)

// ChartPoint is one point of a scatter chart, on the two value axes.
type ChartPoint = tcdata.ChartPoint

// ChartSeries is one named series of a chart.
type ChartSeries = tcdata.ChartSeries

// ChartConf is the configuration for the chart components. The data is not in
// here: labels and series are what a chart is for, so every entry point takes
// them positionally and this carries only the presentation.
type ChartConf = tcdata.ChartConf

// Chart create a chart of the kind [ChartConf.Kind] names, default a line
// chart. Every series needs one value per label.
func Chart(c *tgframe.Container, labels []string, series []ChartSeries, conf ...*ChartConf) {
	tcdata.Chart(c, labels, series, conf...)
}

// LineChart create a line chart, one line per series.
func LineChart(c *tgframe.Container, labels []string, series []ChartSeries, conf ...*ChartConf) {
	tcdata.LineChart(c, labels, series, conf...)
}

// BarChart create a bar chart, one bar per value grouped by label.
func BarChart(c *tgframe.Container, labels []string, series []ChartSeries, conf ...*ChartConf) {
	tcdata.BarChart(c, labels, series, conf...)
}

// AreaChart create an area chart, one filled line per series.
func AreaChart(c *tgframe.Container, labels []string, series []ChartSeries, conf ...*ChartConf) {
	tcdata.AreaChart(c, labels, series, conf...)
}

// ScatterChart create a scatter chart, one marker per point. It takes no
// labels: both of a scatter chart's axes are value axes, so a point carries
// its own x, in [ChartSeries.Points] rather than Values.
func ScatterChart(c *tgframe.Container, series []ChartSeries, conf ...*ChartConf) {
	tcdata.ScatterChart(c, series, conf...)
}

// ColumnType is how a DataFrame column's cells are read, which is what tells
// sorting whether "10" comes before or after "9".
type ColumnType = tcdata.ColumnType

const (
	// ColumnTypeText sorts the cells as strings.
	ColumnTypeText = tcdata.ColumnTypeText

	// ColumnTypeNumber sorts the cells by their numeric value, so "10" sorts
	// after "9". Cells that are not numbers sort last.
	ColumnTypeNumber = tcdata.ColumnTypeNumber

	// ColumnTypeDatetime sorts the cells by the instant they name. Anything
	// the client can parse as a date works, RFC 3339 most reliably. Cells
	// that are not dates sort last.
	ColumnTypeDatetime = tcdata.ColumnTypeDatetime
)

// ColumnAlign is which edge a DataFrame column's cells sit against.
type ColumnAlign = tcdata.ColumnAlign

const (
	// ColumnAlignAuto aligns a ColumnTypeNumber column right, and every
	// other column left.
	ColumnAlignAuto = tcdata.ColumnAlignAuto

	// ColumnAlignLeft aligns the cells left.
	ColumnAlignLeft = tcdata.ColumnAlignLeft

	// ColumnAlignCenter centers the cells.
	ColumnAlignCenter = tcdata.ColumnAlignCenter

	// ColumnAlignRight aligns the cells right.
	ColumnAlignRight = tcdata.ColumnAlignRight
)

// SelectionMode is how many rows of a DataFrame the app user may pick.
//
// Picking a row is the one DataFrame interaction that reruns the page
// function: sorting, searching and paging stay in the browser, but a
// selection is an answer the page has to be given.
type SelectionMode = tcdata.SelectionMode

const (
	// SelectionModeNone leaves the rows unpickable, the default. A DataFrame
	// like this holds no state and always returns an empty selection.
	SelectionModeNone = tcdata.SelectionModeNone

	// SelectionModeSingle lets one row be picked at a time, by clicking it.
	// Clicking the picked row again clears the selection.
	SelectionModeSingle = tcdata.SelectionModeSingle

	// SelectionModeMulti lets any number of rows be picked, through a
	// checkbox column the table grows on the left.
	SelectionModeMulti = tcdata.SelectionModeMulti
)

// DataFrameColumnConf is the configuration of one DataFrame column. It is
// named after the component rather than called ColumnConf because the layout
// Column already has that name.
type DataFrameColumnConf = tcdata.DataFrameColumnConf

// DataFrameConf is the configuration for the DataFrame component. Sorting and
// searching are on unless the conf turns them off, so a DataFrame written
// without a conf is the interactive table the component is for.
type DataFrameConf = tcdata.DataFrameConf

// DataFrame create a table the user can sort, search and page through, and
// return the rows the user has picked, as indices into rows. Sorting,
// searching and paging all happen in the browser, so none of them reruns the
// page function.
//
// Every row needs one cell per head entry. [DataFrameColumnConf] carries what
// the cells mean, so the data stays a plain string matrix.
//
// The rows can only be picked once [DataFrameConf.Selection] says so; until
// then the return is always empty. The indices are into rows, the order the
// page function wrote them in, not the order the table happens to show them
// in, and they come back sorted and without duplicates. The result is empty
// rather than nil when nothing is picked.
//
// An index is a position and not a row identity, the same contract [Select]
// and [MultiSelect] have with their items: when rows changes between runs, an
// index picked against the old data is read against the new one, and only an
// index past the end is dropped. Set [DataFrameConf.RowKeys] to name the rows
// and the selection is remembered by key instead, which is what to do before
// acting on a selection destructively: the return is still positions, but
// positions into the rows of this run, and a row that is gone is dropped
// rather than standing for whatever moved into its place.
//
// [Table] is the static counterpart: reach for it when the rows are few and
// already in the order they should be read in.
//
// [DataFrameCells] is the same table with typed cells, for values whose
// display is not their sort order (a percentage, a missing value).
func DataFrame(c *tgframe.Container, head []string, rows [][]string, conf ...*DataFrameConf) []int {
	return tcdata.DataFrame(c, head, rows, conf...)
}

// DataFrameCells is [DataFrame] with each cell carrying the value it sorts
// by apart from the string it shows, so "29.41%" still sorts as a number
// and a missing value always sorts last. A [NumberCell] belongs in a
// ColumnTypeNumber column and a [TimeCell] in a ColumnTypeDatetime one; a
// cell in any other column fails the run.
func DataFrameCells(c *tgframe.Container, head []string, rows [][]Cell, conf ...*DataFrameConf) []int {
	return tcdata.DataFrameCells(c, head, rows, conf...)
}

// Cell is one DataFrame cell: a value the column sorts by, and the string
// the table shows and searches. Build one with [TextCell], [NumberCell],
// [TimeCell] or [MissingCell].
type Cell = tcdata.Cell

// TextCell is a cell holding s, read the way [DataFrame] reads its strings:
// a number or datetime column still parses it.
func TextCell(s string) Cell {
	return tcdata.TextCell(s)
}

// NumberCell is a cell sorted by v. It is shown through the column's
// [NumberFormat] unless WithDisplay says otherwise. NaN is a missing cell.
// It belongs in a ColumnTypeNumber column.
func NumberCell(v float64) Cell {
	return tcdata.NumberCell(v)
}

// TimeCell is a cell sorted by the instant t, shown as RFC 3339 unless
// WithDisplay says otherwise. It belongs in a ColumnTypeDatetime column.
func TimeCell(t time.Time) Cell {
	return tcdata.TimeCell(t)
}

// MissingCell is a cell with no value. It sorts last whichever direction the
// column is sorted in, and shows empty unless WithDisplay says otherwise.
func MissingCell() Cell {
	return tcdata.MissingCell()
}

// NumberFormat is how a ColumnTypeNumber column shows a [NumberCell] that
// has no display of its own.
type NumberFormat = tcdata.NumberFormat

// JSONConf is the configuration for the JSON component.
type JSONConf = tcdata.JSONConf

// JSON create a JSON viewer for v.
// If v is a string, it will be treated as a JSON string.
// If v is not a string, it will be serialized to a JSON string.
func JSON(c *tgframe.Container, v any, conf ...*JSONConf) {
	tcdata.JSON(c, v, conf...)
}

// TableConf is the configuration for the Table component.
type TableConf = tcdata.TableConf

// Table create a table by heading(head) and values(table).
func Table(c *tgframe.Container, head []string, table [][]string, conf ...*TableConf) {
	tcdata.Table(c, head, table, conf...)
}
