// Code generated by tgcomp/internal/gen; DO NOT EDIT.

package tgcomp

import (
	"github.com/voilelab/toolgui/toolgui/tgcomp/tcinput"
	"github.com/voilelab/toolgui/toolgui/tgframe"
	"time"
)

// ButtonConf is the configuration for the Button component
type ButtonConf = tcinput.ButtonConf

// Button create a button and return true if it's clicked.
func Button(c *tgframe.Container, label string, conf ...*ButtonConf) bool {
	return tcinput.Button(c, label, conf...)
}

// ButtonClicked reports whether the click this run is handling is the one on
// the button label and conf describe. It reads the click, it does not draw the
// button: give it the same label and conf the [Button] call gets.
//
// It reads the click off the run's state rather than off the button, so a page
// can ask before the button is drawn — the case for a button written below the
// content it changes, which would otherwise have to send the old content out
// first and rewrite it.
//
//	if tgcomp.ButtonClicked(c, "Load details") {
//		details = load()
//	}
//	...
//	tgcomp.Button(c, "Load details")
//
// The click id comes from the client, and the page has not drawn anything yet
// to check it against, so the button the last run put on the screen is what
// it's checked against — the same guard an upload naming a component id goes
// through. A click on a button that was not there is not a click.
func ButtonClicked(c *tgframe.Container, label string, conf ...*ButtonConf) bool {
	return tcinput.ButtonClicked(c, label, conf...)
}

// CheckboxConf is the configuration for a checkbox.
type CheckboxConf = tcinput.CheckboxConf

// Checkbox create a checkbox and return true if it's checked.
func Checkbox(c *tgframe.Container, label string, conf ...*CheckboxConf) bool {
	return tcinput.Checkbox(c, label, conf...)
}

// CodeInputConf is the configuration for a code input.
type CodeInputConf = tcinput.CodeInputConf

// CodeInput create a code editor with syntax highlight and return its value.
// The value is sent when the editor loses focus or on Ctrl/Cmd+Enter.
func CodeInput(c *tgframe.Container, label string, conf ...*CodeInputConf) string {
	return tcinput.CodeInput(c, label, conf...)
}

// ColorPickerConf is the configuration for a color picker.
type ColorPickerConf = tcinput.ColorPickerConf

// ColorPicker create a color picker and return the picked color as a lowercase
// "#rrggbb" string. Before anything is picked that is the conf's Default.
//
// A Default that is not an "#rrggbb" color is a mistake in the caller rather
// than a value to correct, and panics.
func ColorPicker(c *tgframe.Container, label string, conf ...*ColorPickerConf) string {
	return tcinput.ColorPicker(c, label, conf...)
}

// DatePickerConf is the configuration for the DatePicker component.
type DatePickerConf = tcinput.DatePickerConf

// DatePicker create a datepicker and return its selected date, as midnight UTC
// on the day picked. Return nil if no date is selected.
//
// Only the day is kept: a clock the caller's Default carried is dropped, the
// way [TimePicker] drops the date, so the three pickers hand back times that
// compare.
func DatePicker(c *tgframe.Container, label string, conf ...*DatePickerConf) *time.Time {
	return tcinput.DatePicker(c, label, conf...)
}

// TimePickerConf is the configuration for the TimePicker component.
type TimePickerConf = tcinput.TimePickerConf

// TimePicker create a timepicker and return its selected time of day, as that
// clock on 1 January year 0 in UTC — only the clock is meaningful. Return nil
// if no time is selected.
//
// Only the clock is kept: a date the caller's Default carried is dropped, the
// way [DatePicker] drops the clock.
func TimePicker(c *tgframe.Container, label string, conf ...*TimePickerConf) *time.Time {
	return tcinput.TimePicker(c, label, conf...)
}

// DateTimePickerConf is the configuration for the DateTimePicker component.
type DateTimePickerConf = tcinput.DateTimePickerConf

// DateTimePicker create a datetimepicker and return its selected datetime,
// read to the minute and in UTC. Return nil if no datetime is selected.
func DateTimePicker(c *tgframe.Container, label string, conf ...*DateTimePickerConf) *time.Time {
	return tcinput.DateTimePicker(c, label, conf...)
}

// DownloadButtonConf is the configuration for the DownloadButton component.
type DownloadButtonConf = tcinput.DownloadButtonConf

// DownloadButton create a download button component.
func DownloadButton(c *tgframe.Container, text string, body []byte, conf ...*DownloadButtonConf) bool {
	return tcinput.DownloadButton(c, text, body, conf...)
}

// DownloadButtonClicked reports whether the click this run is handling is the
// one on the download button text and conf describe. It reads the click, it
// does not draw the button: give it the same text and conf the
// [DownloadButton] call gets. It's [ButtonClicked] for a download button.
//
// It takes no body: the button's id comes from text (or the conf id), not from
// what it hands over, so a page can ask about the click before it has the
// bytes to offer.
func DownloadButtonClicked(c *tgframe.Container, text string, conf ...*DownloadButtonConf) bool {
	return tcinput.DownloadButtonClicked(c, text, conf...)
}

// DownloadFileConf is the configuration for the DownloadFile component.
type DownloadFileConf = tcinput.DownloadFileConf

// DownloadFile create a button that hands the app user a file to download.
//
// The file is stored where the build keeps files -- on disk on a server, in
// the origin private file system in a browser build -- and the component's
// pack carries only an unguessable token to fetch it by. A click fetches the
// bytes through the state's own transport and saves them, so a big output
// costs the transport what it weighs rather than a third again as base64, and
// the link the browser follows is one the page built rather than a URI Go
// sent.
//
// [DownloadButton] is the one to reach for below a few hundred kilobytes: it
// puts the content in the pack as a data: URI, which is a round trip saved on
// a file the pack can carry comfortably. This one is for everything above
// that.
//
// It reports whether this run is handling a click on it, the same as
// [DownloadButton].
func DownloadFile(c *tgframe.Container, text string, body []byte, conf ...*DownloadFileConf) bool {
	return tcinput.DownloadFile(c, text, body, conf...)
}

// DownloadFileFunc is [DownloadFile] with the file made on click rather than
// on every run: gen is called only by the run a click on the button starts,
// and the client saves what it returns once that run's pack arrives. It spares
// a page the "prepare, then download" pair of buttons, and a run that is not
// about the file the cost of building it.
//
// An error from gen is shown under the button, which stays so the app user can
// try again. It reports whether this run is handling a click on it.
func DownloadFileFunc(c *tgframe.Container, text string, gen func() ([]byte, error), conf ...*DownloadFileConf) bool {
	return tcinput.DownloadFileFunc(c, text, gen, conf...)
}

// DownloadFileClicked reports whether the click this run is handling is the
// one on the download file button text and conf describe. It reads the click,
// it does not draw the button: give it the same text and conf the
// [DownloadFile] call gets. It's [ButtonClicked] for a download file button.
//
// It takes no body, for the same reason [DownloadButtonClicked] does not: the
// button's id comes from text (or the conf id), not from the file.
func DownloadFileClicked(c *tgframe.Container, text string, conf ...*DownloadFileConf) bool {
	return tcinput.DownloadFileClicked(c, text, conf...)
}

// FileObject is the object that is returned when a file is uploaded.
//
// The content stays on disk. Read it with [FileObject.Open] to work through a
// stream, or [FileObject.Bytes] to take it whole.
type FileObject = tcinput.FileObject

// FileUploadConf is the configuration for the FileUpload component.
//
// There is no Default here, unlike the other inputs. A file input is the one
// control a page cannot fill in on the app user's behalf: the browser refuses
// to have its value set from script, so a default would read back in Go while
// the box on screen stayed empty. A page that wants to start from a file it
// already has should read that file itself rather than ask for one.
type FileUploadConf = tcinput.FileUploadConf

// FileUpload create a fileupload and return its selected file.
// Return nil if no file is selected.
func FileUpload(c *tgframe.Container, label, accept string, conf ...*FileUploadConf) *FileObject {
	return tcinput.FileUpload(c, label, accept, conf...)
}

// MultiFileUpload create a fileupload that takes more than one file and return
// the selected files, in the order they were picked.
// Return nil if no file is selected.
//
// The i-th file is stored under [tgframe.FileKey] of the component id and i.
func MultiFileUpload(c *tgframe.Container, label, accept string, conf ...*FileUploadConf) []*FileObject {
	return tcinput.MultiFileUpload(c, label, accept, conf...)
}

// FormConf is the configuration for the Form component. The container a form
// hands out derives its id from the form's; give none and it carries none, and
// the components inside are still placed by position.
type FormConf = tcinput.FormConf

// Form create a form component.
//
// The input components inside a form do not rerun the page as they are
// touched: their values are held on the client and sent together when the
// form is submitted, so the page reads a whole set of them at once.
//
// A form is submitted by its built-in submit button, or by a [Button] written
// inside it — a click inside a form carries the held values with it, so the
// page sees the new values on the run the button reports its click.
func Form(c *tgframe.Container, conf ...*FormConf) *tgframe.Container {
	return tcinput.Form(c, conf...)
}

// MenuConf is the configuration for the Menu component.
type MenuConf = tcinput.MenuConf

// Menu create a button with a list of actions behind it, and return the index
// of the item clicked. 0-indexed, return nil if no item is clicked.
//
// The click goes through the same event a [Button] press does, so the index
// is there for exactly the run that handles the click and nil again on the
// next one. Which item it was is the item's own id, derived from the menu's,
// so two menus sharing a label need a Conf.ID between them the way two
// buttons do.
//
// Whether the dropdown is open is the client's, like a popover's: the items
// are written every run, open or not.
func Menu(c *tgframe.Container, label string, items []string, conf ...*MenuConf) *int {
	return tcinput.Menu(c, label, items, conf...)
}

// MultiSelectConf is the configuration for the MultiSelect component.
type MultiSelectConf = tcinput.MultiSelectConf

// MultiSelect create a dropdown list that takes more than one item and return
// the indices of the selected ones, 0-indexed.
//
// The result is ordered by items rather than by the order they were picked in,
// and is nil when nothing is selected — the same "nothing" [Select] hands back,
// so one test reads both.
func MultiSelect(c *tgframe.Container, label string, items []string, conf ...*MultiSelectConf) []int {
	return tcinput.MultiSelect(c, label, items, conf...)
}

// Numeric is the value type a [Number] can hold. It is the state's own
// [tgframe.Numeric]: what a number input holds is what the state reads back,
// so there is one set of types, not two that have to be kept in step.
type Numeric = tcinput.Numeric

// NumberConf is the configuration for a number component. A generic conf
// embeds Base like any other.
type NumberConf[T Numeric] = tcinput.NumberConf[T]

// Number create a number input and return its value, which is always within
// Conf.Min and Conf.Max, and whether that value is the one the app user
// entered.
//
// The input reports a value outside that range rather than enforcing it, so
// the app user keeps seeing what they typed, with the message beside it. What
// they typed is what comes back, so the value here is pulled into the range
// on arrival -- never the last one that happened to be inside it, which the
// page would read as what is on screen now.
//
// Pulling it in keeps the value usable but says nothing about where it came
// from: a Max of 24 reads as 24 whether the app user typed 24 or 999. The
// second return tells those apart, so a page can refuse to act on a number
// nobody entered instead of storing a bound as if it were an answer:
//
//	limit, ok := Number(c, "Limit", conf)
//	if !ok {
//		Text(c, "Enter a limit between 0 and 24.")
//		return nil
//	}
//
// It is false when what arrived is outside Conf.Min or Conf.Max, and when T
// does not hold it as it is: a pasted 1e20 is no int, and a typed 20.9 is no
// int either -- an integral T truncates it to 20, and the client's number box
// takes a decimal whatever T is. Neither is the app user's number, any more
// than a clamped 999 is. With no bounds set and a T that holds whatever
// arrives exactly, it is always true. The value is still worth reading when it
// is false: it is the nearest one T holds inside the range, which is what a
// page that only wants to display something should show.
//
// There is no "nothing entered" state to report: an input nobody has typed in
// reads as Conf.Default, and one the app user has emptied reads as zero. Both
// are answers, so both are true.
func Number[T Numeric](c *tgframe.Container, label string, conf ...*NumberConf[T]) (T, bool) {
	return tcinput.Number[T](c, label, conf...)
}

// RadioConf is the configuration for the Radio component.
type RadioConf = tcinput.RadioConf

// Radio create a group of radio items and return its selected value.
// 0-indexed, return nil if no item is selected.
//
// A radio has no placeholder to reserve an index for, so the state under its
// id is 0-based, unlike [Select]'s. Neither shows through here.
func Radio(c *tgframe.Container, label string, items []string, conf ...*RadioConf) *int {
	return tcinput.Radio(c, label, items, conf...)
}

// SelectConf is the configuration for the Select component.
type SelectConf = tcinput.SelectConf

// Select create a select dropdown list and return its selected value.
// 0-indexed, return nil if no item is selected.
//
// The state under the component's id is 1-based, keeping 0 for "nothing
// selected" because the frontend's first option is a placeholder. That offset
// is entirely internal: both Conf.Default and the return are 0-based, so
// Default: 0 is items[0].
func Select(c *tgframe.Container, label string, items []string, conf ...*SelectConf) *int {
	return tcinput.Select(c, label, items, conf...)
}

// SelectSliderConf is the configuration for the SelectSlider component.
type SelectSliderConf = tcinput.SelectSliderConf

// SelectSlider create a slider over a list of discrete items and return the
// index of the one it sits on, 0-indexed as [Select]'s is.
//
// The handle is always on an item, so it always has an index to hand back: the
// one the app user left it at, else Default. An empty items, or a Default
// outside it, is a mistake in the caller and panics.
func SelectSlider(c *tgframe.Container, label string, items []string, conf ...*SelectSliderConf) int {
	return tcinput.SelectSlider(c, label, items, conf...)
}

// SliderConf is the configuration for a slider component.
type SliderConf[T Numeric] = tcinput.SliderConf[T]

// Slider create a slider over a numeric range and return its value.
//
// A slider always sits somewhere in its range, so it always has a value to
// hand back: the one the app user left it at, else Default, else Min.
//
// The value is reported when the handle is released rather than on every tick
// of a drag, so a drag across the range is one rerun rather than one per step.
//
// A range whose Min is above its Max, or a negative Step, is a mistake in the
// caller rather than a value to correct, and panics.
func Slider[T Numeric](c *tgframe.Container, label string, conf ...*SliderConf[T]) T {
	return tcinput.Slider[T](c, label, conf...)
}

// TextareaConf is the configuration for a textarea.
type TextareaConf = tcinput.TextareaConf

// Textarea create a textarea and return its value.
func Textarea(c *tgframe.Container, label string, conf ...*TextareaConf) string {
	return tcinput.Textarea(c, label, conf...)
}

// TextboxConf is the configuration for the Textbox component
type TextboxConf = tcinput.TextboxConf

// Textbox create a textbox and return its value.
func Textbox(c *tgframe.Container, label string, conf ...*TextboxConf) string {
	return tcinput.Textbox(c, label, conf...)
}

// ToggleConf is the configuration for a toggle.
type ToggleConf = tcinput.ToggleConf

// Toggle create a switch and return true if it's on. It is [Checkbox] drawn as
// a switch: same signature, same value, different affordance.
func Toggle(c *tgframe.Container, label string, conf ...*ToggleConf) bool {
	return tcinput.Toggle(c, label, conf...)
}
