// Code generated by tgcomp/internal/gen; DO NOT EDIT.

package tgcomp

import (
	"github.com/voilelab/toolgui/toolgui/tgcomp/tclayout"
	"github.com/voilelab/toolgui/toolgui/tgframe"
)

// BoxConf is the configuration for the Box component. The container a box
// hands out derives its id from the box's; give none and it carries none, and
// the components inside are still placed by position.
type BoxConf = tclayout.BoxConf

// Box create a box container.
func Box(c *tgframe.Container, conf ...*BoxConf) *tgframe.Container {
	return tclayout.Box(c, conf...)
}

// ColumnConf is the configuration for the column components. The containers a
// column hands out derive their ids from its ID; give none and they carry
// none, and the components inside are still placed by position.
type ColumnConf = tclayout.ColumnConf

// Column create N columns, each as wide as its content needs.
func Column(c *tgframe.Container, n uint, conf ...*ColumnConf) []*tgframe.Container {
	return tclayout.Column(c, n, conf...)
}

// Column1 create 1 column.
func Column1(c *tgframe.Container, conf ...*ColumnConf) *tgframe.Container {
	return tclayout.Column1(c, conf...)
}

// Column2 create 2 columns.
func Column2(c *tgframe.Container, conf ...*ColumnConf) (*tgframe.Container, *tgframe.Container) {
	return tclayout.Column2(c, conf...)
}

// Column3 create 3 columns.
func Column3(c *tgframe.Container, conf ...*ColumnConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.Column3(c, conf...)
}

// EqColumn create N columns with equal width.
func EqColumn(c *tgframe.Container, n uint, conf ...*ColumnConf) []*tgframe.Container {
	return tclayout.EqColumn(c, n, conf...)
}

// EqColumn1 create 1 column.
func EqColumn1(c *tgframe.Container, conf ...*ColumnConf) *tgframe.Container {
	return tclayout.EqColumn1(c, conf...)
}

// EqColumn2 create 2 columns.
func EqColumn2(c *tgframe.Container, conf ...*ColumnConf) (*tgframe.Container, *tgframe.Container) {
	return tclayout.EqColumn2(c, conf...)
}

// EqColumn3 create 3 columns.
func EqColumn3(c *tgframe.Container, conf ...*ColumnConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.EqColumn3(c, conf...)
}

// EqColumn4 create 4 columns.
func EqColumn4(c *tgframe.Container, conf ...*ColumnConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.EqColumn4(c, conf...)
}

// EqColumn5 create 5 columns.
func EqColumn5(c *tgframe.Container, conf ...*ColumnConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.EqColumn5(c, conf...)
}

// The widths a dialog may be given, as the client receives them.
const (
	DialogWidthSmall  = tclayout.DialogWidthSmall
	DialogWidthMedium = tclayout.DialogWidthMedium
	DialogWidthLarge  = tclayout.DialogWidthLarge
)

// DialogConf is the configuration for the Dialog component.
type DialogConf = tclayout.DialogConf

// DialogContainer is what [Dialog] hands out: the dialog it drew, to be
// opened, closed and filled while the page function runs.
type DialogContainer = tclayout.DialogContainer

// Dialog creates a dialog, closed until something opens it, and hands back a
// handle to open, close and fill it:
//
//	d := tgcomp.Dialog(p.Main, "Delete")
//
//	if tgcomp.Button(p.Main, "Delete") {
//		d.Open()
//	}
//
//	d.With(func(c *tgframe.Container) {
//		tgcomp.Text(c, "Delete "+name+"?")
//		if tgcomp.Button(c, "Yes") {
//			remove(name)
//			d.Close()
//		}
//	})
//
// Handle what opens the dialog before calling [DialogContainer.With], as
// above: With is what draws the body, so an Open after it opens a dialog this
// run left empty, and the body only appears on the run after.
//
// Whether the dialog is open is kept by the page rather than the client, so
// it claims an id derived from its title. Two dialogs with the same title
// collide; give one of them a Conf.ID.
//
// Widgets inside the body keep their state while the dialog is closed, as any
// component hidden behind an `if` does. Wrap the body in a
// [github.com/voilelab/toolgui/toolgui/tgcomp.Empty] slot and clear it to
// throw that state away.
func Dialog(c *tgframe.Container, title string, conf ...*DialogConf) *DialogContainer {
	return tclayout.Dialog(c, title, conf...)
}

// EmptyConf is the configuration for the Empty component. The container an
// empty hands out derives its id from the empty's; give none and it carries
// none, and the components inside are still placed by position.
type EmptyConf = tclayout.EmptyConf

// EmptySlot is what [Empty] hands out: a place in the page that can be
// written and written over.
type EmptySlot = tclayout.EmptySlot

// Empty reserves a place in the page and hands back a slot to write it with.
// Writing the slot again takes the previous contents off the screen instead of
// adding to them, so a page function can show progress and then replace it
// with the result:
//
//	slot := tgcomp.Empty(c)
//	slot.With(func(c *tgframe.Container) {
//		tgcomp.Text(c, "Querying…")
//	})
//
//	head, rows := query()
//
//	slot.With(func(c *tgframe.Container) {
//		tgcomp.Table(c, head, rows)
//	})
//
// The slot starts empty on every run, whatever the last run left in it.
func Empty(c *tgframe.Container, conf ...*EmptyConf) *EmptySlot {
	return tclayout.Empty(c, conf...)
}

// ExpandConf is the configuration for the Expand component.
type ExpandConf = tclayout.ExpandConf

// Expand create a expandable component.
func Expand(c *tgframe.Container, title string, expanded bool, conf ...*ExpandConf) *tgframe.Container {
	return tclayout.Expand(c, title, expanded, conf...)
}

// GridDefaultMinColWidth is the column width, in px, a grid uses when its conf
// gives none.
const GridDefaultMinColWidth = tclayout.GridDefaultMinColWidth

// The gaps a grid may leave between its cells, as the client receives them.
const (
	GridGapNone = tclayout.GridGapNone
	GridGapXS   = tclayout.GridGapXS
	GridGapSM   = tclayout.GridGapSM
	GridGapMD   = tclayout.GridGapMD
	GridGapLG   = tclayout.GridGapLG
	GridGapXL   = tclayout.GridGapXL
)

// GridConf is the configuration for the Grid component. The container a grid
// hands out derives its id from the grid's; give none and it carries none.
type GridConf = tclayout.GridConf

// Grid lays what is written into it out in cells of equal width, as many to a
// row as fit, wrapping onto the next row when the width runs out:
//
//	g := tgcomp.Grid(p.Main)
//	for _, m := range metrics {
//		tgcomp.Metric(g, m.Label, m.Value)
//	}
//
// A short last row keeps the width of the rows above.
func Grid(c *tgframe.Container, conf ...*GridConf) *tgframe.Container {
	return tclayout.Grid(c, conf...)
}

// PopoverConf is the configuration for the Popover component.
type PopoverConf = tclayout.PopoverConf

// Popover create a button with a floating panel behind it, and return the
// container the panel holds.
func Popover(c *tgframe.Container, label string, conf ...*PopoverConf) *tgframe.Container {
	return tclayout.Popover(c, label, conf...)
}

// TabConf is the configuration for the Tab components.
type TabConf = tclayout.TabConf

// Tab creates a new tab component
func Tab(c *tgframe.Container, tabs []string, conf ...*TabConf) []*tgframe.Container {
	return tclayout.Tab(c, tabs, conf...)
}

// Tab2 create 2 tabs.
func Tab2(c *tgframe.Container, tab1, tab2 string, conf ...*TabConf) (*tgframe.Container, *tgframe.Container) {
	return tclayout.Tab2(c, tab1, tab2, conf...)
}

// Tab3 create 3 tabs.
func Tab3(c *tgframe.Container, tab1, tab2, tab3 string, conf ...*TabConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.Tab3(c, tab1, tab2, tab3, conf...)
}

// Tab4 create 4 tabs.
func Tab4(c *tgframe.Container, tab1, tab2, tab3, tab4 string, conf ...*TabConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.Tab4(c, tab1, tab2, tab3, tab4, conf...)
}

// Tab5 create 5 tabs.
func Tab5(c *tgframe.Container, tab1, tab2, tab3, tab4, tab5 string, conf ...*TabConf) (*tgframe.Container, *tgframe.Container, *tgframe.Container, *tgframe.Container, *tgframe.Container) {
	return tclayout.Tab5(c, tab1, tab2, tab3, tab4, tab5, conf...)
}

// The ways a toolbar may line its items up, as the client receives them.
const (
	ToolbarJustifyStart   = tclayout.ToolbarJustifyStart
	ToolbarJustifyEnd     = tclayout.ToolbarJustifyEnd
	ToolbarJustifyBetween = tclayout.ToolbarJustifyBetween
)

// ToolbarConf is the configuration for the Toolbar component. The container a
// toolbar hands out derives its id from the toolbar's; give none and it
// carries none, and the components inside are still placed by position.
type ToolbarConf = tclayout.ToolbarConf

// Toolbar creates a row of controls and returns the container they go into.
// What is written inside lines up horizontally, each item as wide as it needs
// to be, rather than taking a row of the page each:
//
//	bar := tgcomp.Toolbar(p.Main, &tgcomp.ToolbarConf{Sticky: true})
//	if tgcomp.Button(bar, "Run") {
//		run()
//	}
//	tgcomp.Select(bar, "Mode", modes)
//
// A row too wide for the viewport wraps instead of pushing the page sideways.
func Toolbar(c *tgframe.Container, conf ...*ToolbarConf) *tgframe.Container {
	return tclayout.Toolbar(c, conf...)
}
