// Code generated by tgcomp/internal/gen; DO NOT EDIT.

package tgcomp

import (
	"github.com/voilelab/toolgui/toolgui/tgcomp/tcmisc"
	"github.com/voilelab/toolgui/toolgui/tgframe"
)

// HTMLConf is the configuration for the HTML component.
type HTMLConf = tcmisc.HTMLConf

// HTML adds an HTML component to the container.
func HTML(c *tgframe.Container, html string, conf ...*HTMLConf) {
	tcmisc.HTML(c, html, conf...)
}

// IframeConf is the configuration for the Iframe component.
type IframeConf = tcmisc.IframeConf

// Iframe shows HTML in a sandboxed iframe.
//
// Read what its guest sends back with [IframeValue].
func Iframe(c *tgframe.Container, html string, conf ...*IframeConf) {
	tcmisc.Iframe(c, html, conf...)
}

// IframeValue returns the latest value the guest of the iframe html and conf
// describe sent through window.toolgui.update. It reads the value, it does not
// draw the iframe: give it the same html and conf the [Iframe] call gets.
//
// It returns nil when the guest has no value for the page, so a page tells
// that apart from a value that is the zero T. A guest that has not sent yet and
// one that sent null both read as nil: null is how a guest says it has nothing,
// not a value of its own.
//
//	if v := tgcomp.IframeValue[picked](c, html, conf); v != nil {
//		use(*v)
//	}
//
// The frontend keys the value by the iframe's own component id, so a guest can
// only write to its own state.
func IframeValue[T any](c *tgframe.Container, html string, conf ...*IframeConf) *T {
	return tcmisc.IframeValue[T](c, html, conf...)
}

// MessageConf provide extra config for Message Component.
type MessageConf = tcmisc.MessageConf

// Message is a component that displays a message.
func Message(c *tgframe.Container, text string, conf ...*MessageConf) {
	tcmisc.Message(c, text, conf...)
}

// MessageInfo is a component that displays a message with info color.
func MessageInfo(c *tgframe.Container, text string, conf ...*MessageConf) {
	tcmisc.MessageInfo(c, text, conf...)
}

// MessageSuccess is a component that displays a message with success color.
func MessageSuccess(c *tgframe.Container, text string, conf ...*MessageConf) {
	tcmisc.MessageSuccess(c, text, conf...)
}

// MessageWarning is a component that displays a message with warning color.
func MessageWarning(c *tgframe.Container, text string, conf ...*MessageConf) {
	tcmisc.MessageWarning(c, text, conf...)
}

// MessageDanger is a component that displays a message with danger color.
func MessageDanger(c *tgframe.Container, text string, conf ...*MessageConf) {
	tcmisc.MessageDanger(c, text, conf...)
}

// PluginConf is the configuration for the Plugin component.
type PluginConf = tcmisc.PluginConf

// Plugin runs the script at src in a sandboxed frame, and hands it props.
//
// The script is loaded from the app itself: register its files with
// [tgframe.App.AddPluginAssets] and name them with [tgframe.PluginAssetURL].
// It runs on an opaque origin, so it cannot reach the app's page, its dom, its
// cookies or its storage; it talks to the app through window.toolgui, the same
// bridge [Iframe] gives its html.
//
// Read what it sends back with [PluginValue].
func Plugin(c *tgframe.Container, src string, conf ...*PluginConf) {
	tcmisc.Plugin(c, src, conf...)
}

// PluginValue returns the latest value the plugin src and conf describe sent
// through window.toolgui.update. It reads the value, it does not draw the
// plugin: give it the same src and conf the [Plugin] call gets, and read
// before drawing when the props depend on the value.
//
//	conf := &tgcomp.PluginConf{ID: "color_picker"}
//	selected := ""
//	if v := tgcomp.PluginValue[color](c, src, conf); v != nil {
//		selected = v.Color
//	}
//
//	conf.Props = map[string]any{"selected": selected}
//	tgcomp.Plugin(c, src, conf)
//
// It returns nil when the plugin has no value for the page, so a page tells
// that apart from a value that is the zero T. A plugin that has not sent yet
// and one that sent null both read as nil: null is how a plugin says it has
// nothing, not a value of its own.
//
// The frontend keys the value by the plugin's own component id, so a plugin
// can only write to its own state.
func PluginValue[T any](c *tgframe.Container, src string, conf ...*PluginConf) *T {
	return tcmisc.PluginValue[T](c, src, conf...)
}

// ProgressBarHandle is what [ProgressBar] hands out: the bar it drew, to be
// moved along while the page function works. It is a value like any other, so
// the work may take it as a parameter or keep it in a struct field:
//
//	type importer struct{ bar *tgcomp.ProgressBarHandle }
type ProgressBarHandle = tcmisc.ProgressBarHandle

// ProgressBarConf is the configuration for the ProgressBar component.
type ProgressBarConf = tcmisc.ProgressBarConf

// ProgressBar creates a new progress bar component.
// Example:
// ```go
// bar := tgcomp.ProgressBar(c, 50, "Progress")
//
//	for i := 0; i <= 100; i++ {
//		bar.SetValue(i)
//		time.Sleep(100 * time.Millisecond)
//	}
//
// bar.SetLabel("Completed")
// ```
func ProgressBar(c *tgframe.Container, value int, label string, conf ...*ProgressBarConf) *ProgressBarHandle {
	return tcmisc.ProgressBar(c, value, label, conf...)
}

// SpinnerConf is the configuration for the Spinner component.
type SpinnerConf = tcmisc.SpinnerConf

// Spinner shows that the page function is busy, and returns the function that
// takes it down again. It sits in an [Empty] slot, so taking it down
// leaves the page as if it had never been there.
//
// Call it with defer and the spinner is taken down however the work ends,
// including a panic:
//
//	defer tgcomp.Spinner(c, "Loading…")()
//
// The returned function may be called more than once; only the first call
// does anything.
func Spinner(c *tgframe.Container, label string, conf ...*SpinnerConf) func() {
	return tcmisc.Spinner(c, label, conf...)
}

// StatusConf is the configuration for the Status component.
type StatusConf = tcmisc.StatusConf

// StatusHandle is what [Status] hands out. It is an expander whose label
// carries the state of the work, and whose contents are the lines written to
// it so far.
//
// It holds an [Empty] slot and rewrites it on every change, so the
// label and the lines are always what the last call left.
type StatusHandle = tcmisc.StatusHandle

// Status reports a piece of work while the page function does it. Write the
// lines as they come, and close it with [StatusHandle.Complete] or
// [StatusHandle.Fail]:
//
//	s := tgcomp.Status(c, "Importing…")
//	for _, f := range files {
//		s.Write(f)
//		importFile(f)
//	}
//	s.Complete("Imported")
//
// A status that is never closed stays in its running state, which is what the
// page should show when the work did not get that far.
func Status(c *tgframe.Container, label string, conf ...*StatusConf) *StatusHandle {
	return tcmisc.Status(c, label, conf...)
}

// ToastConf is the configuration for the Toast component.
type ToastConf = tcmisc.ToastConf

// Toast shows a one-off notification that takes itself off the screen again:
//
//	if tgcomp.Button(c, "Save") {
//		save()
//		tgcomp.Toast(c, "Saved", &tgcomp.ToastConf{Icon: "✅"})
//	}
//
// It leaves a node on the page that renders nothing, so it takes up no room
// and does not move what is around it. Toasts stack in the order they were
// written, and hovering one holds them all on screen.
//
// A toast is fired once per run. Every run that reaches the call fires it
// again, including a run the same button starts a second time, and a run that
// nothing on the page changed -- which is what makes it a notification rather
// than a [Message] that happens to fade. A run that never reaches the call,
// because an `if` above it was false or because the page function failed
// first, fires nothing.
//
// Whether the run that fired it finishes does not matter: a toast the client
// has already been told about lives out its duration there, and an
// interrupted run cannot take it back.
func Toast(c *tgframe.Container, text string, conf ...*ToastConf) {
	tcmisc.Toast(c, text, conf...)
}
