name: GolangCI-Lint

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  golangci-lint:
    name: GolangCI-Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable
          go-version-file: go.mod
          cache-dependency-path: go.sum
      
      - name: Fake build assets
        run: |
          cd toolgui-web
          mkdir -p app/build/static
          echo "fake" > app/build/index.html
          echo "fake" > app/build/static/fake.txt

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.60
