# Govulncheck for push and pull_request, fails the steps if vulnerabilities are found

name: Govulncheck

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest
    name: Vulnerability Scan
    steps:
    - uses: golang/govulncheck-action@v1
      with:
        go-package: ./...
